<?php
/**
 * Created by PhpStorm.
 * User: Mopkau
 * Date: 08.10.2017
 * Time: 19:33
 */

namespace notifier;


class Module extends \yii\base\Module
{
    const TYPE_SMS = "Sms";
    const TYPE_EMAIL = "Email";

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

}